version: '2'
services:
 zookeeper:
   image: confluentinc/cp-zookeeper:7.0.1
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000


 kafka:
   image: confluentinc/cp-kafka:7.0.1
   depends_on:
     - zookeeper
   ports:
     - "9092:9092"
     - "9094:9094"
   environment:
     KAFKA_SCHEMA_REGISTRY_URL: "schema-registry:8081"
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


 schema-registry:
   image: confluentinc/cp-schema-registry:latest
   depends_on:
     - kafka
   ports:
     - "8081:8081"
   environment:
     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


 kafka-ui:
   image: provectuslabs/kafka-ui
   depends_on:
     - kafka
   ports:
     - "8080:8080"
   environment:
     KAFKA_CLUSTERS_0_NAME: local
     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181