services:
  kafka-0:
    image: bitnami/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_SCHEMA_REGISTRY_URL=schema-registry:8081
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9096,2@kafka-2:9099
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_practicum_0_data:/bitnami/kafka
  kafka-1:
    image: bitnami/kafka:3.4
    ports:
      - "9097:9097"
    environment:
      - KAFKA_SCHEMA_REGISTRY_URL=schema-registry:8081
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9096,2@kafka-2:9099
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9095,CONTROLLER://:9096,EXTERNAL://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9095,EXTERNAL://127.0.0.1:9097
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_practicum_1_data:/bitnami/kafka
  kafka-2:
    image: bitnami/kafka:3.4
    ports:
      - "9100:9100"
    environment:
      - KAFKA_SCHEMA_REGISTRY_URL=schema-registry:8081
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9096,2@kafka-2:9099
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9098,CONTROLLER://:9099,EXTERNAL://:9100
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9098,EXTERNAL://127.0.0.1:9100
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_practicum_2_data:/bitnami/kafka
  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9095,kafka-2:9098
      - KAFKA_CLUSTERS_0_NAME=kraft
  schema-registry:
   image: confluentinc/cp-schema-registry:latest
   depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
   ports:
     - "8081:8081"
   environment:
     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-0:9092
     SCHEMA_REGISTRY_HOST_NAME: schema-registry
     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  app:
   build:
    context: .
    dockerfile: Dockerfile
   deploy:
    mode: replicated
    replicas: 2
   depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
     - schema-registry
   ports:
     - "3002-3003:3002"

volumes:
  kafka_practicum_0_data:
  kafka_practicum_1_data:
  kafka_practicum_2_data: