# BUILD STAGE
FROM golang:latest AS builder

WORKDIR /user_message_project

COPY ../user_message_project/ .

RUN go mod download && go mod verify

RUN go build -o app_single_message_consumer ./cmd/producer/producer.go

# RUN STAGE
FROM ubuntu:24.04 AS runner

WORKDIR /user_message_project

COPY --from=builder /user_message_project/app_single_message_consumer .

CMD ["/user_message_project/app_single_message_consumer", "-mode=release"]