# BUILD STAGE
FROM golang:latest AS builder

WORKDIR /user_message_project

COPY ../user_message_project/ .

RUN go mod download && go mod verify

RUN go build -o app_batch_message_consumer ./cmd/batch_message_consumer/batch_message_consumer.go

# RUN STAGE
FROM ubuntu:24.04 AS runner

WORKDIR /user_message_project

COPY --from=builder /user_message_project/app_batch_message_consumer .

CMD ["/user_message_project/app_batch_message_consumer", "-mode=release"]