services:
 zookeeper:
   ports:
     - "127.0.0.1:22181:2181"
   container_name: zookeeper
   image: confluentinc/cp-zookeeper:7.4.4
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
   networks:
     - kafka-network


 kafka-1:
   image: confluentinc/cp-kafka:7.4.4
   container_name: kafka-1
   ports:
     - "127.0.0.1:29092:29092"
   depends_on:
     - zookeeper
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   networks:
     - kafka-network


 kafka-2:
   image: confluentinc/cp-kafka:7.4.4
   container_name: kafka-2
   ports:
     - "127.0.0.1:39092:39092"
   depends_on:
     - zookeeper
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   networks:
     - kafka-network


 kafka-3:
   image: confluentinc/cp-kafka:7.4.4
   container_name: kafka-3
   ports:
     - "127.0.0.1:49092:49092"
   depends_on:
     - zookeeper
   environment:
     KAFKA_BROKER_ID: 3
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   networks:
     - kafka-network


networks:
 kafka-network:
   driver: bridge